services:

  mex:
    build: ./build
    container_name: mex
    restart: unless-stopped
    network_mode: host
    environment:
       - WAIT_TIME=7200                # Interval für den Abruf in Sekunden
       - USERNAME=uuuuu@gmail.com      # Deine Email Adresse bei HeizOel24
       - PASSWORD=ppppppppp            # Dein Passwort bei HeizOel24
       - MEX_ID=1                      # Falls mehrere MEX Geräte, hier ID eintragen (2, 3, 4, ...)
       - BROKER_ADDRESS=192.168.1.50   # MQTT Broker IP (da wo der MQTT Broker läuft)
       - MQTT_USER=xxxxxx              # MQTT User      (im MQTT Broker definiert)
       - MQTT_PASS=yyyyyy              # MQTT Passwort  (im MQTT Broker definiert)
       - MQTT_PORT=1883                # MQTT Port      (default: 1883)
       - REFERENCE_MONTH=6   # Stichmonat (Monatsende) für Jahresverbrauchs Berechnung (1-12) 0 deaktiviert die Übertragung der Jahresverbrauchs Daten
       - MQTT_ACTIVE=True    # Auf False, wenn nichts MQTT published werden soll
       - LESS_DATA=True      # Weniger Zukunftsdaten abrufen (nur alle 14 Tage)
       - CREATE_JSON=False   # True erstellt:  CalculatedRemaining.json, ,OilUsage.json,   Items.json
       - JSON_PATH="/data"   # Pfad für die Json Datei. Standardpfad ist bei Script.  sonst zBsp.: JSON_PATH = "/home/pi/"
       - DELAY=False         # Auf True setzen, wenn der MQTT Broker nur die 1. Zeile empfängt
       - DEBUG=False         # True = Debug Infos auf die Konsole.  Unbedingt nach debuggen zurück setzen!!
    volumes:
       - ./data:/data
